<?php

namespace cnct\facpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProcessusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessusRepository extends EntityRepository
{
}