<?php

namespace cnct\facpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
    public function getTotal()
    {
        $qb = $this->createQueryBuilder('u')
                   ->select('COUNT(u)');     // On sélectionne simplement COUNT(a)

        return (int) $qb->getQuery()
                         ->getSingleScalarResult(); // Utilisation de getSingleScalarResult pour avoir directement le résultat du COUNT
    }
}